version: '3.8'

services:
  client:
    image: nawinscript/client:latest
    ports:
      - "5000:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  server:
    image: nawinscript/server:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 